language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm ci

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

before_deploy:
  - sed -i '/dist\//d' .gitignore
